### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by Hoxolotl** [SimplyEdit/simplyedit#15]
Sorry USERNAME it seems that my mail server is not responding. Please try again later!

Couldn't figure out how to get the forms working although there is a contact_me.php that I edited as good as I could.

**Comment by poef** [comment]
This is part of the template. I think the template could use an update where this is easier to setup. But really, a contact form that sends email is no longer a good idea, with spambots getting much more sophisticated. It should probably just have a mailto: action.
