### ISSUE TITLE
save button leads to user cache issue

### ISSUE THREAD

**Issue by Hoxolotl** [SimplyEdit/simplyedit#19]
When pressing the save button the browser should reload the entire page.

Currently when users press save, and open a new tab in the same browser they are seeing their "old" content from before the save.

Suggestion: 
add a 
location.reload();
or
window.location.reload();

https://developer.mozilla.org/en-US/docs/Web/API/Location/reload

**Comment by ylebre** [comment]
I disagree with this idea. Pressing save should save the data and keep the state 'as is', not do a total reload of the page. If the page on the other tab is showing outdated content, that would be because of caching on the server side, which is not something handled by simplyEdit.
